[workspace]
resolver = "2"
members = [
    "framework",
    "roll",
    "ceiling",
    "plus",
    "minus",
    "lcm",
    "bang",
    "decode",
    "multiply",
    "divide",
    "encode",
    "circle",
    "equal",
    "not",
    "power",
]
